import type { Metadata } from "next";
import { Baloo_Bhaijaan_2} from "next/font/google";
import "./globals.css";

const baloo = Baloo_Bhaijaan_2({
  variable: "--font-baloo",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "PractiPuma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baloo.variable} ${baloo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
