import type { Metadata } from "next";
import { Baloo_Bhaijaan_2} from "next/font/google";
import "./globals.css";
// import { Header } from "@/components/common/Header";
import { ThemeProvider } from "next-themes";
// import { PageTransition } from "@/components/common/PageTransitions";

const baloo = Baloo_Bhaijaan_2({
  variable: "--font-baloo",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "PractiPuma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-MX" suppressHydrationWarning>
      <body
        className={`${baloo.variable} ${baloo.variable} antialiased`}
      >
      <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem={true}   
      >
        {/* <Header/> */}
        {/* <PageTransition> */}
          {children}
        {/* </PageTransition> */}
      </ThemeProvider>
      </body>
    </html>
  );
}
